# Generated by Django 5.2.17 on 2026-09-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0002_approved_stores_online"),
        ("catalog", "0002_productimage_variant_offer_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="featured_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_in_stores",
                to="catalog.product",
            ),
        ),
    ]
