# Generated by Django 5.2.17 on 2026-09-05 05:31

from django.db import migrations, models

import apps.businesses.models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0003_storesettings_featured_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="contact_address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="logo",
            field=models.FileField(blank=True, upload_to=apps.businesses.models.store_logo_path),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="privacy_policy",
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="return_refund_policy",
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="terms_conditions",
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="tiktok_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="x_url",
            field=models.URLField(blank=True),
        ),
    ]
