# Generated by Django 5.2.17 on 2026-09-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0004_storesettings_contact_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="mpesa_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="stripe_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
