# Generated by Django 5.2.17 on 2026-09-09 03:20

from django.db import migrations, models

import apps.businesses.models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_storesettings_mpesa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='cover',
            field=models.FileField(blank=True, upload_to=apps.businesses.models.store_cover_path),
        ),
    ]
