# Generated by Django 5.2.17 on 2026-09-09 03:40

from html import escape

from django.db import migrations, models


def preserve_plain_text(apps, schema_editor):
    StoreSettings = apps.get_model("businesses", "StoreSettings")
    for store in StoreSettings.objects.all().iterator():
        changed = []
        for field in ["description", "terms_conditions", "privacy_policy", "return_refund_policy"]:
            value = getattr(store, field)
            if "<" in value or ">" in value:
                setattr(store, field, "<p>" + escape(value).replace("\n", "<br>") + "</p>")
                changed.append(field)
        if changed:
            store.save(update_fields=changed)


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0006_storesettings_cover"),
    ]

    operations = [
        migrations.RunPython(preserve_plain_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="storesettings",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="privacy_policy",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="return_refund_policy",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="terms_conditions",
            field=models.TextField(blank=True),
        ),
    ]
