# Generated by Django 5.2.17 on 2026-09-05 06:11

import uuid

from django.db import migrations, models

import simulator.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=simulator.models.session_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("order_id", models.UUIDField(unique=True)),
                ("store_name", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                ("provider", models.CharField(max_length=12)),
                ("return_url", models.URLField(max_length=500)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("order_status", models.CharField(default="pending", max_length=16)),
                ("event_id", models.UUIDField(null=True)),
                ("delivered", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
    ]
