# Generated by Django 5.2.17 on 2026-09-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='backend',
            field=models.CharField(default='simulator', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='initiation_state',
            field=models.CharField(default='new', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
