# Generated by Django 5.2.17 on 2026-09-09 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_paymentsession_backend_paymentsession_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(max_length=12)),
                ('encrypted_values', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='business_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='simulator.paymentconfiguration'),
        ),
    ]
