# Generated by Django 5.2.17 on 2026-09-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_paymentconfiguration_paymentsession_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='encrypted_credentials',
            field=models.TextField(blank=True),
        ),
    ]
