# Generated by Django 5.2.17 on 2026-09-05 04:52

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to=apps.catalog.models.product_image_path)),
                ("original_name", models.CharField(max_length=180)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="variant",
            name="offer_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("offer_price__isnull", True),
                    models.Q(("offer_price__gte", 0), ("offer_price__lt", models.F("price"))),
                    _connector="OR",
                ),
                name="variant_offer_below_price",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
            ),
        ),
    ]
