# Generated by Django 5.2.17 on 2026-09-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_productimage_variant_offer_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variant",
            options={"ordering": ["position", "id"]},
        ),
        migrations.AddField(
            model_name="product",
            name="has_variants",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="variant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="variant",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
