/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_list"];
        put?: never;
        post: operations["applications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["applications_partial_update"];
        trace?: never;
    };
    "/api/applications/{id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applications_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/setup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_mfa_setup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_mfa_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/cover/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["businesses_cover_create"];
        delete: operations["businesses_cover_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/customers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_customers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/domains/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_domains_list"];
        put?: never;
        post: operations["businesses_domains_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/domains/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["businesses_domains_destroy"];
        options?: never;
        head?: never;
        patch: operations["businesses_domains_partial_update"];
        trace?: never;
    };
    "/api/businesses/{business_id}/logo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["businesses_logo_create"];
        delete: operations["businesses_logo_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_orders_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/orders/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["businesses_orders_partial_update"];
        trace?: never;
    };
    "/api/businesses/{business_id}/payments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_payments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/payments/configuration/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_payments_configuration_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["businesses_payments_configuration_partial_update"];
        trace?: never;
    };
    "/api/businesses/{business_id}/payments/providers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_payments_providers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/payments/wallet/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_payments_wallet_retrieve"];
        put?: never;
        post: operations["businesses_payments_wallet_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/payments/withdrawals/{withdrawal_id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["businesses_payments_withdrawals_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_preview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/preview-link/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["businesses_preview_link_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_products_list"];
        put?: never;
        post: operations["businesses_products_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/products/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_products_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["businesses_products_partial_update"];
        trace?: never;
    };
    "/api/businesses/{business_id}/products/{id}/images/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["businesses_products_images_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/products/{id}/images/{image_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["businesses_products_images_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/promotions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_promotions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/promotions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["businesses_promotions_partial_update"];
        trace?: never;
    };
    "/api/businesses/{business_id}/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["businesses_settings_partial_update"];
        trace?: never;
    };
    "/api/businesses/{business_id}/staff/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_staff_list"];
        put?: never;
        post: operations["businesses_staff_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/businesses/{business_id}/staff/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["businesses_staff_destroy"];
        options?: never;
        head?: never;
        patch: operations["businesses_staff_partial_update"];
        trace?: never;
    };
    "/api/businesses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["businesses_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["businesses_partial_update"];
        trace?: never;
    };
    "/api/cart/quote/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cart_quote_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkout/handoff/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkout_handoff_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{token}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/checkout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payments_checkout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/webhooks/dummy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payments_webhooks_dummy_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["platform_applications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["platform_applications_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/applications/{id}/retry-provisioning/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["platform_applications_retry_provisioning_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/applications/{id}/review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["platform_applications_review_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/wallet/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["platform_wallet_retrieve"];
        put?: never;
        post: operations["platform_wallet_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/withdrawals/{withdrawal_id}/review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["platform_withdrawals_review_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product-images/{image_id}/content/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["product_images_content_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store-covers/{business_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["store_covers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store-logos/{business_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["store_logos_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storefront/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["storefront_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storefront/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["storefront_preview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Application: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
            category: string;
            phone: string;
            country: string;
            currency: string;
            description?: string;
            readonly status: components["schemas"]["ApplicationStatusEnum"];
            readonly review_note: string;
            /** Format: date-time */
            readonly submitted_at: string | null;
            /** Format: date-time */
            readonly reviewed_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: email */
            readonly owner_email: string;
            /** Format: uuid */
            readonly business: string | null;
            readonly provisioning_status: string;
        };
        ApplicationRequest: {
            name: string;
            slug: string;
            category: string;
            phone: string;
            country: string;
            currency: string;
            description?: string;
        };
        /**
         * @description * `draft` - Draft
         *     * `pending` - Pending review
         *     * `changes_requested` - Changes requested
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         * @enum {string}
         */
        ApplicationStatusEnum: "draft" | "pending" | "changes_requested" | "approved" | "rejected";
        Business: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
            country: string;
            currency: string;
            provisioning_status?: string;
            suspended?: boolean;
            published?: boolean;
            readonly role: string;
            readonly domains: components["schemas"]["Domain"][];
            readonly storefront_url: string;
        };
        CartItemRequest: {
            /** Format: uuid */
            variant_id: string;
            quantity: number;
        };
        CheckoutRequest: {
            items: components["schemas"]["CartItemRequest"][];
            /** Format: uuid */
            checkout_key: string;
            quote_token: string;
            name: string;
            /** Format: email */
            email: string;
            /** @default  */
            phone: string;
            address: string;
            provider: components["schemas"]["ProviderEnum"];
        };
        CodeRequest: {
            code: string;
        };
        Customer: {
            /** Format: email */
            email: string;
            order_count: number;
            /** Format: decimal */
            paid_total: string;
            /** Format: date-time */
            last_order: string;
        };
        /**
         * @description * `approved` - approved
         *     * `changes_requested` - changes_requested
         *     * `rejected` - rejected
         * @enum {string}
         */
        DecisionEnum: "approved" | "changes_requested" | "rejected";
        Detail: {
            detail: string;
        };
        Domain: {
            hostname: string;
            verified?: boolean;
            is_primary?: boolean;
        };
        DomainAdmin: {
            readonly id: number;
            hostname: string;
            readonly verified: boolean;
            readonly is_primary: boolean;
        };
        DomainAdminRequest: {
            hostname: string;
        };
        /**
         * @description * `unfulfilled` - unfulfilled
         *     * `processing` - processing
         *     * `shipped` - shipped
         *     * `delivered` - delivered
         * @enum {string}
         */
        FulfillmentStatusEnum: "unfulfilled" | "processing" | "shipped" | "delivered";
        HandoffInputRequest: {
            token: string;
            details?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResult: {
            user?: components["schemas"]["User"];
            requires_mfa?: boolean;
            requires_mfa_setup?: boolean;
        };
        LogoUploadRequest: {
            /** Format: binary */
            image: string;
        };
        MerchantOrder: {
            /** Format: uuid */
            readonly id: string;
            readonly customer_name: string;
            /** Format: email */
            readonly email: string;
            readonly phone: string;
            readonly address: string;
            readonly currency: string;
            /** Format: decimal */
            readonly subtotal: string;
            /** Format: decimal */
            readonly tax: string;
            /** Format: decimal */
            readonly total: string;
            readonly provider: string;
            readonly status: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly fulfillment_status: string;
            readonly staff_notes: string;
            readonly tracking_reference: string;
            readonly lines: components["schemas"]["OrderLineAdmin"][];
        };
        MerchantPayment: {
            /** Format: uuid */
            readonly id: string;
            readonly customer_name: string;
            /** Format: email */
            readonly email: string;
            readonly provider: string;
            readonly status: string;
            /** Format: decimal */
            readonly total: string;
            readonly currency: string;
            readonly session_id: string;
            readonly payment_backend: string;
            readonly payment_review_required: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        MfaSetup: {
            secret: string;
            provisioning_uri: string;
        };
        OrderLineAdmin: {
            readonly id: number;
            product_name: string;
            variant_name: string;
            /** Format: int64 */
            quantity: number;
            /** Format: decimal */
            unit_price: string;
            /** Format: decimal */
            line_total: string;
        };
        PaginatedApplicationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Application"][];
        };
        PaginatedBusinessList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Business"][];
        };
        PaginatedCustomerList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Customer"][];
        };
        PaginatedDomainAdminList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DomainAdmin"][];
        };
        PaginatedMerchantOrderList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MerchantOrder"][];
        };
        PaginatedMerchantPaymentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MerchantPayment"][];
        };
        PaginatedProductList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Product"][];
        };
        PaginatedPromotionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Promotion"][];
        };
        PaginatedStaffList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Staff"][];
        };
        PatchedApplicationRequest: {
            name?: string;
            slug?: string;
            category?: string;
            phone?: string;
            country?: string;
            currency?: string;
            description?: string;
        };
        PatchedBusinessNameRequest: {
            name?: string;
        };
        PatchedDomainPrimaryRequest: {
            is_primary?: boolean;
        };
        PatchedFulfillmentRequest: {
            fulfillment_status?: components["schemas"]["FulfillmentStatusEnum"];
            staff_notes?: string;
            tracking_reference?: string;
        };
        PatchedOfferRequest: {
            /** Format: decimal */
            offer_price?: string | null;
        };
        PatchedPaymentSettingsInputRequest: {
            provider?: components["schemas"]["ProviderEnum"];
            values?: {
                [key: string]: unknown;
            };
        };
        PatchedProductCreateRequest: {
            name?: string;
            /** @default draft */
            status: components["schemas"]["ProductCreateStatusEnum"];
            /** @default  */
            category: string;
            /** @default  */
            description: string;
            has_variants?: boolean;
            variants?: components["schemas"]["VariantInputRequest"][];
            /** Format: decimal */
            price?: string;
            /** Format: decimal */
            offer_price?: string | null;
            stock?: number;
        };
        PatchedSettingsRequest: {
            headline?: string;
            description?: string;
            /** Format: email */
            contact_email?: string;
            /** Format: decimal */
            tax_rate?: string;
            stripe_enabled?: boolean;
            mpesa_enabled?: boolean;
            contact_phone?: string;
            contact_address?: string;
            whatsapp_number?: string;
            /** Format: uri */
            instagram_url?: string;
            /** Format: uri */
            facebook_url?: string;
            /** Format: uri */
            tiktok_url?: string;
            /** Format: uri */
            x_url?: string;
            /** Format: uri */
            linkedin_url?: string;
            return_refund_policy?: string;
            privacy_policy?: string;
            terms_conditions?: string;
            surface_tone?: components["schemas"]["SurfaceToneEnum"];
            published?: boolean;
            /** Format: uuid */
            featured_product?: string | null;
        };
        PatchedStaffRoleRequest: {
            role?: components["schemas"]["RoleEnum"];
        };
        Product: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            readonly slug: string;
            description?: string;
            category?: string;
            status?: components["schemas"]["ProductStatusEnum"];
            has_variants?: boolean;
            readonly variants: components["schemas"]["Variant"][];
            readonly images: components["schemas"]["ProductImage"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        ProductCreateRequest: {
            name: string;
            /** @default draft */
            status: components["schemas"]["ProductCreateStatusEnum"];
            /** @default  */
            category: string;
            /** @default  */
            description: string;
            has_variants?: boolean;
            variants?: components["schemas"]["VariantInputRequest"][];
            /** Format: decimal */
            price?: string;
            /** Format: decimal */
            offer_price?: string | null;
            stock?: number;
        };
        /**
         * @description * `draft` - draft
         *     * `published` - published
         * @enum {string}
         */
        ProductCreateStatusEnum: "draft" | "published";
        ProductImage: {
            /** Format: uuid */
            readonly id: string;
            readonly url: string;
            readonly original_name: string;
            readonly width: number;
            readonly height: number;
        };
        ProductImageUploadRequest: {
            /** Format: binary */
            image: string;
        };
        /**
         * @description * `draft` - Draft
         *     * `published` - Published
         * @enum {string}
         */
        ProductStatusEnum: "draft" | "published";
        Promotion: {
            /** Format: uuid */
            readonly id: string;
            readonly product_name: string;
            readonly product_status: string;
            readonly label: string;
            /** Format: decimal */
            readonly price: string;
            /** Format: decimal */
            readonly offer_price: string | null;
        };
        /**
         * @description * `stripe` - stripe
         *     * `mpesa` - mpesa
         * @enum {string}
         */
        ProviderEnum: "stripe" | "mpesa";
        QuoteRequest: {
            items: components["schemas"]["CartItemRequest"][];
        };
        RegisterRequest: {
            first_name: string;
            /** @default  */
            last_name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        ReviewRequest: {
            decision: components["schemas"]["DecisionEnum"];
            /** @default  */
            note: string;
        };
        /**
         * @description * `owner` - Owner
         *     * `manager` - Manager
         *     * `fulfillment` - Fulfillment
         *     * `support` - Support
         * @enum {string}
         */
        RoleEnum: "owner" | "manager" | "fulfillment" | "support";
        Settings: {
            headline?: string;
            description?: string;
            /** Format: email */
            contact_email?: string;
            /** Format: decimal */
            tax_rate?: string;
            stripe_enabled?: boolean;
            mpesa_enabled?: boolean;
            contact_phone?: string;
            contact_address?: string;
            whatsapp_number?: string;
            readonly logo_url: string;
            readonly cover_url: string;
            /** Format: uri */
            instagram_url?: string;
            /** Format: uri */
            facebook_url?: string;
            /** Format: uri */
            tiktok_url?: string;
            /** Format: uri */
            x_url?: string;
            /** Format: uri */
            linkedin_url?: string;
            return_refund_policy?: string;
            privacy_policy?: string;
            terms_conditions?: string;
            readonly theme_id: string;
            surface_tone: components["schemas"]["SurfaceToneEnum"];
            published?: boolean;
            /** Format: uuid */
            featured_product?: string | null;
        };
        SettlementInputRequest: {
            /** Format: uuid */
            order_id: string;
            /** Format: decimal */
            amount: string;
            reference: string;
        };
        Staff: {
            readonly id: number;
            readonly user_id: number;
            /** Format: email */
            readonly email: string;
            readonly name: string;
            readonly role: components["schemas"]["RoleEnum"];
        };
        StaffAddRequest: {
            /** Format: email */
            email: string;
            role: components["schemas"]["RoleEnum"];
        };
        /**
         * @description * `taupe` - taupe
         *     * `sky` - sky
         *     * `mauve` - mauve
         *     * `olive` - olive
         *     * `cream` - cream
         * @enum {string}
         */
        SurfaceToneEnum: "taupe" | "sky" | "mauve" | "olive" | "cream";
        Token: {
            token: string;
        };
        TokenRequest: {
            token: string;
        };
        User: {
            readonly id: number;
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            email_verified?: boolean;
            /**
             * Staff status
             * @description Designates whether the user can log into this admin site.
             */
            is_staff?: boolean;
        };
        Variant: {
            /** Format: uuid */
            readonly id: string;
            sku: string;
            label?: string;
            /** Format: decimal */
            price: string;
            /** Format: decimal */
            offer_price?: string | null;
            /** Format: int64 */
            stock?: number;
        };
        VariantInputRequest: {
            /** Format: uuid */
            id?: string;
            label: string;
            /** Format: decimal */
            price: string;
            /** Format: decimal */
            offer_price?: string | null;
            stock?: number;
        };
        WebhookRequest: {
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            order_id: string;
            session_id: string;
            provider: components["schemas"]["ProviderEnum"];
            status: components["schemas"]["WebhookStatusEnum"];
            /** Format: decimal */
            amount: string;
            currency: string;
        };
        /**
         * @description * `succeeded` - succeeded
         *     * `failed` - failed
         * @enum {string}
         */
        WebhookStatusEnum: "succeeded" | "failed";
        Withdrawal: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly business_id: string;
            readonly business_name: string;
            /** Format: decimal */
            readonly amount: string;
            readonly currency: string;
            readonly method: components["schemas"]["WithdrawalMethodEnum"];
            readonly recipient_name: string;
            readonly phone: string;
            readonly bank_name: string;
            readonly account_number: string;
            readonly status: components["schemas"]["WithdrawalStatusEnum"];
            readonly transfer_reference: string;
            readonly review_note: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly reviewed_at: string | null;
        };
        /**
         * @description * `mpesa` - mpesa
         *     * `bank` - bank
         * @enum {string}
         */
        WithdrawalInputMethodEnum: "mpesa" | "bank";
        WithdrawalInputRequest: {
            /** Format: uuid */
            request_key: string;
            /** Format: decimal */
            amount: string;
            method: components["schemas"]["WithdrawalInputMethodEnum"];
            recipient_name: string;
            /** @default  */
            phone: string;
            /** @default  */
            bank_name: string;
            /** @default  */
            account_number: string;
        };
        /**
         * @description * `mpesa` - M-Pesa
         *     * `bank` - Bank
         * @enum {string}
         */
        WithdrawalMethodEnum: "mpesa" | "bank";
        WithdrawalReviewInputRequest: {
            status: components["schemas"]["WithdrawalReviewInputStatusEnum"];
            /** @default  */
            transfer_reference: string;
            /** @default  */
            review_note: string;
        };
        /**
         * @description * `completed` - completed
         *     * `rejected` - rejected
         * @enum {string}
         */
        WithdrawalReviewInputStatusEnum: "completed" | "rejected";
        /**
         * @description * `pending` - Pending
         *     * `completed` - Completed
         *     * `rejected` - Rejected
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        WithdrawalStatusEnum: "pending" | "completed" | "rejected" | "cancelled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    applications_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedApplicationList"];
                };
            };
        };
    };
    applications_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ApplicationRequest"];
                "multipart/form-data": components["schemas"]["ApplicationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this business application. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this business application. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedApplicationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedApplicationRequest"];
                "multipart/form-data": components["schemas"]["PatchedApplicationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_submit_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this business application. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_mfa_setup_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaSetup"];
                };
            };
        };
    };
    auth_mfa_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CodeRequest"];
                "multipart/form-data": components["schemas"]["CodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRequest"];
                "multipart/form-data": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    businesses_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBusinessList"];
                };
            };
        };
    };
    businesses_cover_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["LogoUploadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    businesses_cover_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    businesses_customers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCustomerList"];
                };
            };
        };
    };
    businesses_domains_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDomainAdminList"];
                };
            };
        };
    };
    businesses_domains_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainAdminRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DomainAdminRequest"];
                "multipart/form-data": components["schemas"]["DomainAdminRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainAdmin"];
                };
            };
        };
    };
    businesses_domains_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A unique integer value identifying this domain. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    businesses_domains_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A unique integer value identifying this domain. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDomainPrimaryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDomainPrimaryRequest"];
                "multipart/form-data": components["schemas"]["PatchedDomainPrimaryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainAdmin"];
                };
            };
        };
    };
    businesses_logo_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["LogoUploadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    businesses_logo_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    businesses_orders_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMerchantOrderList"];
                };
            };
        };
    };
    businesses_orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A UUID string identifying this order. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOrder"];
                };
            };
        };
    };
    businesses_orders_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A UUID string identifying this order. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedFulfillmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedFulfillmentRequest"];
                "multipart/form-data": components["schemas"]["PatchedFulfillmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantOrder"];
                };
            };
        };
    };
    businesses_payments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMerchantPaymentList"];
                };
            };
        };
    };
    businesses_payments_configuration_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    businesses_payments_configuration_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPaymentSettingsInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPaymentSettingsInputRequest"];
                "multipart/form-data": components["schemas"]["PatchedPaymentSettingsInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    businesses_payments_providers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    businesses_payments_wallet_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    businesses_payments_wallet_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawalInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WithdrawalInputRequest"];
                "multipart/form-data": components["schemas"]["WithdrawalInputRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Withdrawal"];
                };
            };
        };
    };
    businesses_payments_withdrawals_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                withdrawal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Withdrawal"];
                };
            };
        };
    };
    businesses_preview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    businesses_preview_link_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url?: string;
                    };
                };
            };
        };
    };
    businesses_products_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductList"];
                };
            };
        };
    };
    businesses_products_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductCreateRequest"];
                "multipart/form-data": components["schemas"]["ProductCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    businesses_products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    businesses_products_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProductCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProductCreateRequest"];
                "multipart/form-data": components["schemas"]["PatchedProductCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    businesses_products_images_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ProductImageUploadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductImageUploadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImage"];
                };
            };
        };
    };
    businesses_products_images_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A UUID string identifying this product. */
                id: string;
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    businesses_promotions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPromotionList"];
                };
            };
        };
    };
    businesses_promotions_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A UUID string identifying this variant. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOfferRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOfferRequest"];
                "multipart/form-data": components["schemas"]["PatchedOfferRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Promotion"];
                };
            };
        };
    };
    businesses_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    businesses_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSettingsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSettingsRequest"];
                "multipart/form-data": components["schemas"]["PatchedSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    businesses_staff_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStaffList"];
                };
            };
        };
    };
    businesses_staff_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffAddRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StaffAddRequest"];
                "multipart/form-data": components["schemas"]["StaffAddRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
        };
    };
    businesses_staff_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A unique integer value identifying this membership. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    businesses_staff_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
                /** @description A unique integer value identifying this membership. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStaffRoleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStaffRoleRequest"];
                "multipart/form-data": components["schemas"]["PatchedStaffRoleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
        };
    };
    businesses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this business. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
        };
    };
    businesses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this business. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBusinessNameRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBusinessNameRequest"];
                "multipart/form-data": components["schemas"]["PatchedBusinessNameRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Business"];
                };
            };
        };
    };
    cart_quote_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["QuoteRequest"];
                "multipart/form-data": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    checkout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckoutRequest"];
                "multipart/form-data": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    checkout_handoff_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["QuoteRequest"];
                "multipart/form-data": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    payments_checkout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["HandoffInputRequest"];
                "multipart/form-data": components["schemas"]["HandoffInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    payments_webhooks_dummy_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WebhookRequest"];
                "multipart/form-data": components["schemas"]["WebhookRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    platform_applications_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedApplicationList"];
                };
            };
        };
    };
    platform_applications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this business application. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    platform_applications_retry_provisioning_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this business application. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    platform_applications_review_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this business application. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReviewRequest"];
                "multipart/form-data": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    platform_wallet_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    platform_wallet_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettlementInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SettlementInputRequest"];
                "multipart/form-data": components["schemas"]["SettlementInputRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    platform_withdrawals_review_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                withdrawal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawalReviewInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WithdrawalReviewInputRequest"];
                "multipart/form-data": components["schemas"]["WithdrawalReviewInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Withdrawal"];
                };
            };
        };
    };
    product_images_content_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    store_covers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
        };
    };
    store_logos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
        };
    };
    storefront_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    storefront_preview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
