# Generated by Django 5.2.17 on 2026-09-05 06:11

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.checkout.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businesses", "0005_storesettings_mpesa_enabled_and_more"),
        ("catalog", "0003_alter_variant_options_product_has_variants_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.checkout.models.access_token, max_length=64, unique=True
                    ),
                ),
                ("checkout_key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("customer_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(max_length=500)),
                ("currency", models.CharField(max_length=3)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=14)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("provider", models.CharField(max_length=12)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("payment_url", models.URLField(blank=True, max_length=500)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="businesses.business"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_name", models.CharField(max_length=180)),
                ("variant_name", models.CharField(max_length=120)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="checkout.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.variant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="checkout.order"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("business", "checkout_key"), name="unique_checkout_request"
            ),
        ),
    ]
