# Generated by Django 5.2.17 on 2026-09-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(default='unfulfilled', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_notes',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
