# Generated by Django 5.2.17 on 2026-09-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_fulfillment_status_order_staff_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_backend',
            field=models.CharField(default='simulator', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_review_required',
            field=models.BooleanField(default=False),
        ),
    ]
